<a href="https://colab.research.google.com/github/224986/Colab/blob/main/Actividad_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Leonel Jose Evans Gononzalez 
#2249868
#Ciencia de datos Primavera 2023
#Actividad 5
#Prof: Dr. BUSTIO MARTINEZ, LAZARO
#El objetivo es sacar el promedio de n nuemros guardarlos en un arreglo de np despeus en un archio pickle y de nuevo descargalo 
import numpy as np
import pickle as pk
print("Esribe los numeros a los que quieres sacar promedio, cuando termines escribe Termine , el uso de otra palabra o caracter no sera valido y el programa dejara de correr")
numeros = np.array([]).astype(np.float) #se delcara como array de numpy
while True : #while infinito
 num = input('Ingresa un número: ')
 if num == 'Termine' : break #condicion para romper el while infinito 
 valor = float(num) #casteo
 numeros= np.append(numeros, valor)#forma de meter valores al arreglo np
 print(numeros)
promedio = np.mean(numeros) #Usamos funcion pre determiandna de numpy
print('Promedio:', promedio) #salida 1 el promedio

pk.dump(numeros, open("numeros.pkl", "wb+"))#Se guarda del arreglo en numeros en un archivo pickle
recuperado = pk.load(open("numeros.pkl", "rb+" ) )# Se abre y asigna el arreglo de pickle 
print("El arreglo es:")
print(recuperado) #salida 2 el arreglo recuperado del promedio

<ipython-input-1-3178bb33601c>:10: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  numeros = np.array([]).astype(np.float) #se delcara como array de numpy


Esribe los numeros a los que quieres sacar promedio, cuando termines escribe Termine , el uso de otra palabra o caracter no sera valido y el programa dejara de correr
Ingresa un número: 4
[4.]
Ingresa un número: 5
[4. 5.]
Ingresa un número: 6
[4. 5. 6.]
Ingresa un número: 8
[4. 5. 6. 8.]
Ingresa un número: 3
[4. 5. 6. 8. 3.]
Ingresa un número: 9
[4. 5. 6. 8. 3. 9.]
Ingresa un número: 3.4
[4.  5.  6.  8.  3.  9.  3.4]
Ingresa un número: 32.54
[ 4.    5.    6.    8.    3.    9.    3.4  32.54]
Ingresa un número: Termine
Promedio: 8.8675
El arreglo es:
[ 4.    5.    6.    8.    3.    9.    3.4  32.54]


In [ ]:
print("quiero un comit")